FROM python:3.6-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN mkdir /code1 /code2 /code3
RUN pip install --upgrade pip

RUN apt-get update -y
RUN apt-get install -y tar git curl nano wget dialog net-tools build-essential

RUN git clone https://github.com/anonyxhappie/microservice-one
RUN git clone https://github.com/anonyxhappie/microservice-two
RUN git clone https://github.com/anonyxhappie/microservice-three
RUN pip install -r /microservice-one/requirements.txt

COPY .env microservice-one/
COPY .env microservice-two/
COPY .env microservice-three/

COPY start.sh .
RUN chmod +x start.sh

EXPOSE 8000 8001 8002

CMD [ "/start.sh" ]
