version: '3'

services:
  one:
    container_name: one
    hostname: one
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.mq
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 5672:5672
      - 15672:15672
    command: python /microservice-one/project_dir/manage.py runserver 0.0.0.0:8000 & && python /microservice-one/project_dir/scripts/consumer.py &
